### ISSUE TITLE
mainnet example

### ISSUE THREAD

**Issue by benjyz** [valinsky/bloxplorer#9]
would be useful to have in the docs some more examples with mainnet

```
>>> from bloxplorer import bitcoin_explorer
>>> b = explorer.blocks
>>> b.get_last_hash().data
'0000000015e913893a0ebdf6f8f9f30c6f10629de22f809dee37396b98c53dec'
>>> lh = b.get_last_hash().data
>>> lastblock = explorer.blocks.get(lh)
>>> lastblock.data['tx_count']
48
>>> lasttxs = explorer.blocks.get_txs(lh).data
>>> for x in lasttxs: print (x['txid'])
0d89b157a1b97f4990b202ef51c9a8356ca89675e65a5cd0db1620cd471da75b
```

**Comment by valinsky** [comment]
Hello there,

Every method available is documented under the API section of the documentation here https://valinsky.me/bloxplorer/api.html

Do you think i should add more examples about certain methods? If so, which ones would you like to see?
